config/routes.rb
Rails.application.routes.draw do
    root 'books#index'
    get '/' => 'books#index'
    get 'books/:id',to: 'books#detail'
    post 'books/search' => 'books#search'
    resources :books do
  
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title,  presence: true, length: { maximum: 100 }
  validates :summary, presence: true, length: { maximum: 200 }
  validates :author, presence: true, length: { maximum: 20 }
  validates :url,    presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #def hello
   # render html: "hello, world!"
  #end
  #def home
  #end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def detail
    @book = Book.find(params[:id])
  end
  def index
    @book = Book.all
  end
  def search
    @book = Book.where("title like ?", "%" + params[:title] + "%")
    render :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/detail.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>詳細</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
 
  <div class="row">
  <aside class="col-md-4">
  <section class="book_info">
  <%= @book.title %><br>
  <%= @book.author %><br>
  <%= @book.summary %><br>
  <%= link_to "購入はこちら", @book.url, :target => "_blank" %><br>
 
  <h1><button class=""><%= link_to "トップページ", root_path %></button></h1>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
  
  <div><%= debug(params) if Rails.env.development? %></div>
</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>一覧</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <h1>Booker</h1>
    <%= form_tag '/books/search' do %>
    <%= text_field_tag :title,params[:title] %><%#titleという名前のカラムからtitleのパラメータ取得%>
    <%= submit_tag 'Search', :name => nil %>
    <% end %>
    
    <% @book.each do |book| %>
    <%=link_to book.title,book_path(book) %><br>
    <%= book.author %><br>
    <%= book.summary %><br>
    <%end%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一覧</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   
  <%= yield %>

</body>
</html>